(()=>{
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const W=()=>myPermission!=='read_only'&&!isGlobalView;
async function A(u,o){const r=await authFetch(u,o),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||`Request failed (${r.status})`);return d}
function PDF(t,h,b){if(!window.jspdf?.jsPDF)return alert('PDF library unavailable.');const d=new jspdf.jsPDF({orientation:h.length>5?'landscape':'portrait'});d.setFontSize(17);d.text(t,14,18);d.setFontSize(8);d.text(`Generated ${new Date().toLocaleString('en-IN')}`,14,25);d.autoTable({startY:31,head:[h],body:b,styles:{fontSize:8}});d.save(t.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.pdf')}
function nav(){document.querySelectorAll('.alg-head-group[data-head="examination"] .alg-head-items').forEach(x=>{x.querySelector('[data-module="seating"] span:last-child')?.replaceChildren(document.createTextNode('Seating'));x.querySelector('[data-module="invigilation"] span:last-child')?.replaceChildren(document.createTextNode('Invigilation'));if(!x.querySelector('[data-module="results"]'))[['results','▣','Results'],['history','◷','History']].forEach(([m,i,l])=>{const b=document.createElement('button');b.dataset.module=m;b.className='sidebar-item alg-child w-full text-left px-6 py-3 text-xs font-extrabold uppercase text-gray-300 flex items-center space-x-3';b.innerHTML=`<span>${i}</span><span>${l}</span>`;b.onclick=()=>window.switchModule(m,b);x.appendChild(b)})})}
const ob=window.buildGroupedSidebar;if(ob&&!window.__examBuild){window.buildGroupedSidebar=function(){ob.apply(this,arguments);nav()};window.__examBuild=true}
const os=window.switchModule;if(os&&!window.__examSwitch){window.switchModule=async function(m,b){if(m==='results'||m==='history'){currentModule=m;document.querySelectorAll('.sidebar-item').forEach(x=>x.classList.remove('active'));b?.classList.add('active');return m==='results'?results(document.getElementById('mainContent')):history(document.getElementById('mainContent'))}return os.apply(this,arguments)};window.__examSwitch=true}
async function results(c){c.innerHTML=`<div class="space-y-6"><div><h2 class="text-2xl font-black uppercase gold-gradient-text">Results</h2><p class="text-xs text-gray-400 mt-1 uppercase tracking-widest">Batchwise examination results</p></div><div class="glass-panel border gold-border rounded-2xl p-6"><div class="grid md:grid-cols-5 gap-4"><label class="text-xs text-gray-400">Batch<select id="RB" class="mt-2 w-full bg-[#0c0c0c] border gold-border rounded-xl p-3"></select></label><label class="text-xs text-gray-400">Subject(s)<input id="RS" class="mt-2 w-full bg-[#0c0c0c] border gold-border rounded-xl p-3"></label><label class="text-xs text-gray-400">Topic(s)<input id="RT" class="mt-2 w-full bg-[#0c0c0c] border gold-border rounded-xl p-3"></label><label class="text-xs text-gray-400">Exam Date<input id="RD" type="date" class="mt-2 w-full bg-[#0c0c0c] border gold-border rounded-xl p-3"></label><label class="text-xs text-gray-400">Overall Marks<input id="RO" type="number" min="1" step=".01" class="mt-2 w-full bg-[#0c0c0c] border gold-border rounded-xl p-3"></label></div><button ${W()?'':'disabled'} onclick="generateResults()" class="mt-5 gold-bg text-black font-extrabold px-5 py-2.5 rounded-xl text-xs uppercase">Import Batch Students</button><div id="RERR" class="auth-error"></div></div><div id="RP"></div></div>`;const bs=await A(`/api/exams/result-batches/${currentBranchId}`);RB.innerHTML=(Array.isArray(bs)?bs:[]).map(x=>`<option>${E(x)}</option>`).join('')||'<option>No batches found</option>';}
window.generateResults=async()=>{try{const rows=await A('/api/exams/results/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({branch_id:currentBranchId,batch_name:RB.value,subjects:RS.value,topics:RT.value,exam_date:RD.value,overall_marks:Number(RO.value)})});renderResultRows(rows)}catch(e){RERR.textContent=e.message}};
function renderResultRows(rows){if(!rows.length)return;const f=rows[0];RS.value=f.subjects;RT.value=f.topics;RD.value=f.exam_date;RO.value=f.overall_marks;window.RESULT_ROWS=rows;RP.innerHTML=`<div class="glass-panel border gold-border rounded-2xl p-6 overflow-x-auto"><div class="flex justify-between mb-5"><div><h3 class="text-xl font-black gold-gradient-text">${E(f.batch_name)}</h3><p class="text-sm text-gray-400">${E(f.subjects)} · ${E(f.topics)} · ${E(f.exam_date)}</p></div><div class="text-right"><div class="text-[10px] uppercase text-gray-500">Overall Marks</div><div class="text-2xl font-black gold-gradient-text">${E(f.overall_marks)}</div><button onclick="downloadResultsPDF()" class="mt-2 bg-[#141414] border gold-border px-4 py-2 rounded-lg text-xs font-bold uppercase gold-gradient-text">Download PDF</button></div></div><table class="w-full text-left text-sm"><thead class="bg-[#121212] text-xs uppercase gold-gradient-text"><tr><th class="p-4">Student Name</th><th class="p-4">Roll Number</th><th class="p-4">Marks / ${E(f.overall_marks)}</th>${W()?'<th class="p-4">Actions</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr class="border-b border-gray-900"><td class="p-4">${E(r.student_name)}</td><td class="p-4">${E(r.roll_number||'')}</td><td class="p-4"><input id="M${r.id}" type="number" min="0" max="${E(r.overall_marks)}" step=".01" value="${r.marks??''}" ${W()?'':'disabled'} class="w-32 bg-[#0c0c0c] border gold-border rounded-lg p-2"></td>${W()?`<td class="p-4"><button onclick="saveResult(${r.id})" class="gold-gradient-text mr-3">Save</button><button onclick="editResult(${r.id})" class="row-delete-btn mr-3">✎</button><button onclick="deleteResult(${r.id})" class="row-delete-btn">🗑</button></td>`:''}</tr>`).join('')}</tbody></table></div>`}
window.saveResult=async id=>{const f=RESULT_ROWS[0],v=document.getElementById('M'+id).value;await A(`/api/exams/results/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({subjects:RS.value,topics:RT.value,exam_date:RD.value,overall_marks:Number(RO.value),marks:v===''?null:Number(v)})})};
window.editResult=async id=>{const r=RESULT_ROWS.find(x=>x.id===id);const subjects=prompt('Subject(s):',r.subjects);if(subjects===null)return;const topics=prompt('Topic(s):',r.topics);if(topics===null)return;const date=prompt('Exam Date:',r.exam_date);if(date===null)return;const overall=Number(prompt('Overall Marks:',r.overall_marks));if(!overall)return;await A(`/api/exams/results/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({subjects,topics,exam_date:date,overall_marks:overall,marks:document.getElementById('M'+id).value===''?null:Number(document.getElementById('M'+id).value)})});renderResultRows(await A(`/api/exams/results/${currentBranchId}?batch_name=${encodeURIComponent(r.batch_name)}`))};
window.deleteResult=async id=>{if(!confirm('Delete this result record?'))return;const r=RESULT_ROWS.find(x=>x.id===id);await A(`/api/exams/results/${id}`,{method:'DELETE'});renderResultRows(await A(`/api/exams/results/${currentBranchId}?batch_name=${encodeURIComponent(r.batch_name)}`))};
window.downloadResultsPDF=()=>{const r=RESULT_ROWS||[];if(r.length)PDF(`Results - ${r[0].batch_name}`,['Student','Roll Number',`Marks / ${r[0].overall_marks}`],r.map(x=>[x.student_name,x.roll_number||'',x.marks??'']))};
async function history(c){c.innerHTML=`<div class="space-y-6"><div class="flex justify-between"><div><h2 class="text-2xl font-black uppercase gold-gradient-text">History</h2><p class="text-xs text-gray-400 mt-1 uppercase tracking-widest">Examination history register</p></div><button onclick="downloadHistoryPDF()" class="bg-[#141414] border gold-border px-4 py-2 rounded-lg text-xs font-bold uppercase gold-gradient-text">Download PDF</button></div>${W()?`<div class="glass-panel border gold-border rounded-2xl p-6"><div class="grid md:grid-cols-4 gap-4"><input id="HS" placeholder="Subject" class="bg-[#0c0c0c] border gold-border rounded-xl p-3"><input id="HT" placeholder="Topic" class="bg-[#0c0c0c] border gold-border rounded-xl p-3"><input id="HB" placeholder="Batch Name" class="bg-[#0c0c0c] border gold-border rounded-xl p-3"><input id="HD" type="date" class="bg-[#0c0c0c] border gold-border rounded-xl p-3"></div><button onclick="addHistory()" class="mt-4 gold-bg text-black font-extrabold px-5 py-2.5 rounded-xl text-xs uppercase">Add Record</button><div id="HERR" class="auth-error"></div></div>`:''}<div class="glass-panel border gold-border rounded-2xl p-6 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-[#121212] text-xs uppercase gold-gradient-text"><tr><th class="p-4">Subject</th><th class="p-4">Topic</th><th class="p-4">Batch Name</th><th class="p-4">Date</th>${W()?'<th class="p-4">Actions</th>':''}</tr></thead><tbody id="HBDY"></tbody></table></div></div>`;await loadHistory()}
async function loadHistory(){const rows=await A(`/api/exams/history/${currentBranchId}`);window.HISTORY_ROWS=rows;HBDY.innerHTML=rows.map(r=>`<tr class="border-b border-gray-900"><td class="p-4">${E(r.subject)}</td><td class="p-4">${E(r.topic)}</td><td class="p-4">${E(r.batch_name)}</td><td class="p-4">${E(r.exam_date)}</td>${W()?`<td class="p-4"><button onclick="editHistory(${r.id})" class="row-delete-btn mr-3">✎</button><button onclick="deleteHistory(${r.id})" class="row-delete-btn">🗑</button></td>`:''}</tr>`).join('')||'<tr><td colspan="5" class="p-8 text-center text-gray-500">No examination history.</td></tr>'}
window.addHistory=async()=>{try{await A('/api/exams/history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({branch_id:currentBranchId,subject:HS.value,topic:HT.value,batch_name:HB.value,exam_date:HD.value})});await loadHistory()}catch(e){HERR.textContent=e.message}};
window.editHistory=async id=>{const r=HISTORY_ROWS.find(x=>x.id===id);const subject=prompt('Subject:',r.subject);if(subject===null)return;const topic=prompt('Topic:',r.topic);if(topic===null)return;const batch=prompt('Batch Name:',r.batch_name);if(batch===null)return;const date=prompt('Exam Date:',r.exam_date);if(date===null)return;await A(`/api/exams/history/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,topic,batch_name:batch,exam_date:date})});await loadHistory()};
window.deleteHistory=async id=>{if(!confirm('Delete this exam history record?'))return;await A(`/api/exams/history/${id}`,{method:'DELETE'});await loadHistory()};
window.downloadHistoryPDF=()=>PDF('Examination History',['Subject','Topic','Batch Name','Date'],(HISTORY_ROWS||[]).map(r=>[r.subject,r.topic,r.batch_name,r.exam_date]));
nav();setTimeout(nav,500);setTimeout(nav,1500)
})();
