(() => {
  const H = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const canWrite = () => typeof myPermission === 'undefined' || (myPermission !== 'read_only' && !isGlobalView);
  const api = async (url, options={}) => { const r=await authFetch(url, options); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.detail || `Request failed (${r.status})`); return d; };

  function examinationButtons() {
    const groups=document.querySelectorAll('.alg-head-group[data-head="examination"] .alg-head-items');
    groups.forEach(items=>{
      if(items.querySelector('[data-module="results"]')) return;
      const labels=[['results','▣','Results'],['history','◷','History']];
      labels.forEach(([m,i,l])=>{
        const b=document.createElement('button'); b.type='button'; b.dataset.module=m; b.className='sidebar-item alg-child w-full text-left px-6 py-3 text-xs font-extrabold uppercase text-gray-300 flex items-center space-x-3';
        b.innerHTML=`<span>${i}</span><span>${l}</span>`; b.onclick=()=>window.switchModule(m,b); items.appendChild(b);
      });
      items.querySelectorAll('[data-module="seating"], [data-module="invigilation"]').forEach(b=>{ if(b.dataset.module==='seating') b.querySelector('span:last-child').textContent='Seating'; if(b.dataset.module==='invigilation') b.querySelector('span:last-child').textContent='Invigilation'; });
    });
  }

  function exportPDF(title, columns, rows) {
    const {jsPDF}=window.jspdf||{}; if(!jsPDF){alert('PDF library is unavailable.');return;}
    const doc=new jsPDF({orientation:columns.length>5?'landscape':'portrait'}); doc.setFontSize(18); doc.text(title,14,18); doc.setFontSize(9); doc.text(`Generated ${new Date().toLocaleString('en-IN')}`,14,25);
    if(doc.autoTable) doc.autoTable({startY:32,head:[columns],body:rows,styles:{fontSize:8},headStyles:{fontStyle:'bold'}}); else doc.text('PDF table plugin unavailable',14,35);
    doc.save(`${title.replace(/\s+/g,'-').toLowerCase()}.pdf`);
  }

  async function renderResults(container){
    container.innerHTML=`<div class="space-y-6"><div><h2 class="text-2xl font-black uppercase gold-gradient-text tracking-wide">Results</h2><p class="text-xs text-gray-400 mt-1 uppercase tracking-widest">Create an examination result sheet batchwise</p></div>
      <div class="glass-panel border gold-border rounded-2xl p-6"><div class="grid md:grid-cols-5 gap-4">
      <div><label class="block text-xs uppercase text-gray-400 mb-2">Batch Name</label><input id="resultBatch" class="w-full bg-[#0c0c0c] border gold-border rounded-xl p-3 text-sm" placeholder="Batch"></div>
      <div><label class="block text-xs uppercase text-gray-400 mb-2">Subject(s)</label><input id="resultSubject" class="w-full bg-[#0c0c0c] border gold-border rounded-xl p-3 text-sm" placeholder="Physics, Chemistry"></div>
      <div><label class="block text-xs uppercase text-gray-400 mb-2">Topic(s)</label><input id="resultTopic" class="w-full bg-[#0c0c0c] border gold-border rounded-xl p-3 text-sm" placeholder="Current Electricity"></div>
      <div><label class="block text-xs uppercase text-gray-400 mb-2">Exam Date</label><input id="resultDate" type="date" class="w-full bg-[#0c0c0c] border gold-border rounded-xl p-3 text-sm"></div>
      <div><label class="block text-xs uppercase text-gray-400 mb-2">Overall Marks</label><input id="resultOverall" type="number" min="1" step="0.01" class="w-full bg-[#0c0c0c] border gold-border rounded-xl p-3 text-sm" placeholder="100"></div></div>
      <div class="mt-5 flex justify-end"><button ${canWrite()?'':'disabled'} onclick="createExamResultSheet()" class="gold-bg text-black font-extrabold px-5 py-2.5 rounded-xl text-xs uppercase">Import Batch Students</button></div><div id="resultError" class="auth-error"></div></div><div id="resultSheet"></div></div>`;
  }

  window.createExamResultSheet=async()=>{ try{ const b=document.getElementById('resultBatch').value.trim(),s=document.getElementById('resultSubject').value.trim(),t=document.getElementById('resultTopic').value.trim(),d=document.getElementById('resultDate').value,o=document.getElementById('resultOverall').value; const r=await api(`/api/examination/results/${currentBranchId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({batch_name:b,subject:s,topic:t,exam_date:d,overall_marks:o})}); await loadResults(r.id); }catch(e){document.getElementById('resultError').textContent=e.message;} };

  async function loadResults(openId=null){ const exams=await api(`/api/examination/results/${currentBranchId}`); const exam=openId?exams.find(x=>x.id===openId):exams[0]; const sheet=document.getElementById('resultSheet'); if(!sheet)return; if(!exam){sheet.innerHTML='<div class="glass-panel border gold-border rounded-2xl p-8 text-center text-gray-500">No result sheets created yet.</div>';return;}
    document.getElementById('resultBatch').value=exam.batch_name;document.getElementById('resultSubject').value=exam.subject;document.getElementById('resultTopic').value=exam.topic;document.getElementById('resultDate').value=exam.exam_date;document.getElementById('resultOverall').value=exam.overall_marks;
    sheet.innerHTML=`<div class="glass-panel border gold-border rounded-2xl p-6"><div class="flex justify-between items-start gap-4 mb-5"><div><div class="text-xs text-gray-500 uppercase tracking-widest">${H(exam.exam_date)}</div><h3 class="text-xl font-black gold-gradient-text">${H(exam.subject)}</h3><p class="text-sm text-gray-400">${H(exam.topic)} • Batch: ${H(exam.batch_name)}</p></div><div class="text-right"><div class="text-[10px] uppercase text-gray-500">Total Overall Marks</div><div class="text-2xl font-black gold-gradient-text">${H(exam.overall_marks)}</div><button onclick="downloadResultsPDF(${exam.id})" class="mt-2 bg-[#141414] border gold-border px-4 py-2 rounded-lg text-xs font-bold uppercase gold-gradient-text">Download PDF</button></div></div>
      <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-[#121212] text-xs uppercase gold-gradient-text"><tr><th class="p-4">Student</th><th class="p-4">Roll Number</th><th class="p-4">Marks / ${H(exam.overall_marks)}</th><th class="p-4"></th></tr></thead><tbody>${exam.students.map(s=>`<tr class="border-b border-gray-900"><td class="p-4 font-medium">${H(s.student_name)}</td><td class="p-4 text-gray-400">${H(s.roll_number)}</td><td class="p-4"><input id="mark-${s.id}" type="number" min="0" max="${H(exam.overall_marks)}" step="0.01" value="${s.marks??''}" ${canWrite()?'':'disabled'} class="w-28 bg-[#0c0c0c] border gold-border rounded-lg p-2"><button ${canWrite()?'':'disabled'} onclick="saveExamMark(${s.id})" class="ml-2 text-xs gold-gradient-text font-bold">Save</button></td><td class="p-4 text-right"><button ${canWrite()?'':'disabled'} onclick="deleteExamResult(${s.id})" class="row-delete-btn">🗑</button></td></tr>`).join('')}</tbody></table></div></div>`;
  }
  window.saveExamMark=async(id)=>{try{await api(`/api/examination/results/records/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({marks:document.getElementById(`mark-${id}`).value})});}catch(e){alert(e.message)}};
  window.deleteExamResult=async(id)=>{if(!confirm('Delete this student result record?'))return;try{await api(`/api/examination/results/records/${id}`,{method:'DELETE'});await loadResults();}catch(e){alert(e.message)}};
  window.downloadResultsPDF=async(id)=>{const exams=await api(`/api/examination/results/${currentBranchId}`),e=exams.find(x=>x.id===id);if(!e)return;exportPDF(`Results - ${e.batch_name}`,['Student','Roll Number',`Marks / ${e.overall_marks}`],e.students.map(s=>[s.student_name,s.roll_number,s.marks??'']));};

  async function renderHistory(container){container.innerHTML=`<div class="space-y-6"><div class="flex justify-between items-start"><div><h2 class="text-2xl font-black uppercase gold-gradient-text tracking-wide">History</h2><p class="text-xs text-gray-400 mt-1 uppercase tracking-widest">Examination history</p></div><button onclick="downloadHistoryPDF()" class="bg-[#141414] border gold-border px-4 py-2 rounded-lg text-xs font-bold uppercase gold-gradient-text">Download PDF</button></div>
  <div class="glass-panel border gold-border rounded-2xl p-6"><div class="grid md:grid-cols-4 gap-4 mb-5"><input id="historySubject" placeholder="Subject" class="bg-[#0c0c0c] border gold-border rounded-xl p-3 text-sm"><input id="historyTopic" placeholder="Topic" class="bg-[#0c0c0c] border gold-border rounded-xl p-3 text-sm"><input id="historyBatch" placeholder="Batch Name" class="bg-[#0c0c0c] border gold-border rounded-xl p-3 text-sm"><input id="historyDate" type="date" class="bg-[#0c0c0c] border gold-border rounded-xl p-3 text-sm"></div><button ${canWrite()?'':'disabled'} onclick="addHistoryRecord()" class="gold-bg text-black font-extrabold px-5 py-2.5 rounded-xl text-xs uppercase">Add History Record</button><div id="historyError" class="auth-error mt-2"></div></div><div class="glass-panel border gold-border rounded-2xl p-6 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-[#121212] text-xs uppercase gold-gradient-text"><tr><th class="p-4">Subject</th><th class="p-4">Topic</th><th class="p-4">Batch</th><th class="p-4">Date</th><th class="p-4"></th></tr></thead><tbody id="historyBody"></tbody></table></div></div>`;await loadHistory();}
  window.addHistoryRecord=async()=>{try{const s=document.getElementById('historySubject').value.trim(),t=document.getElementById('historyTopic').value.trim(),b=document.getElementById('historyBatch').value.trim(),d=document.getElementById('historyDate').value; if(!s||!t||!b||!d)throw Error('Subject, topic, batch and date are required.'); await api(`/api/examination/results/${currentBranchId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject:s,topic:t,batch_name:b,exam_date:d,overall_marks:1})}); await loadHistory();}catch(e){document.getElementById('historyError').textContent=e.message;}};
  async function loadHistory(){const body=document.getElementById('historyBody');if(!body)return;const rows=await api(`/api/examination/history/${currentBranchId}`);body.innerHTML=rows.map(r=>`<tr class="border-b border-gray-900"><td class="p-4">${H(r.subject)}</td><td class="p-4">${H(r.topic)}</td><td class="p-4">${H(r.batch_name)}</td><td class="p-4">${H(r.exam_date)}</td><td class="p-4 text-right">${canWrite()?`<button onclick="editHistory(${r.id})" class="row-delete-btn mr-3">✎</button><button onclick="deleteHistory(${r.id})" class="row-delete-btn">🗑</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="p-8 text-center text-gray-500">No examination history.</td></tr>';}
  window.editHistory=async(id)=>{const rows=await api(`/api/examination/history/${currentBranchId}`),r=rows.find(x=>x.id===id);if(!r)return;const s=prompt('Subject:',r.subject);if(s===null)return;const t=prompt('Topic:',r.topic);if(t===null)return;const b=prompt('Batch:',r.batch_name);if(b===null)return;const d=prompt('Date (YYYY-MM-DD):',r.exam_date);if(d===null)return;await api(`/api/examination/history/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject:s,topic:t,batch_name:b,exam_date:d})});await loadHistory();};
  window.deleteHistory=async(id)=>{if(!confirm('Delete this examination history record and its result sheet?'))return;await api(`/api/examination/history/${id}`,{method:'DELETE'});await loadHistory();};
  window.downloadHistoryPDF=async()=>{const rows=await api(`/api/examination/history/${currentBranchId}`);exportPDF('Examination History',['Subject','Topic','Batch','Date'],rows.map(r=>[r.subject,r.topic,r.batch_name,r.exam_date]));};

  const oldBuild=window.buildGroupedSidebar;
  if(oldBuild && !window.__examBuildWrapped){window.buildGroupedSidebar=function(){oldBuild.apply(this,arguments);examinationButtons();};window.__examBuildWrapped=true;}
  const oldSwitch=window.switchModule;
  if(oldSwitch && !window.__examSwitchWrapped){window.switchModule=async function(moduleName,btn){if(moduleName==='results'||moduleName==='history'){currentModule=moduleName;document.querySelectorAll('.sidebar-item').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const c=document.getElementById('mainContent');if(moduleName==='results')await renderResults(c);else await renderHistory(c);return;}if(moduleName==='seating'&&btn)btn.querySelector('span:last-child').textContent='Seating';if(moduleName==='invigilation'&&btn)btn.querySelector('span:last-child').textContent='Invigilation';return oldSwitch.apply(this,arguments);};window.__examSwitchWrapped=true;}
  examinationButtons(); setTimeout(examinationButtons,500); setTimeout(examinationButtons,1500);
})();
